### ISSUE TITLE
Arrayrun with system parameters spread to 2 lines won't run

### ISSUE THREAD

**Issue by henhok** [sivanni/CxSystem#38]
For some reason, the parser seems to lose parameters/lines when trying to use arrayrun and system parameters on 2 (or more?) different lines

NameError: Variable multidimension_array_run not found in the configuration file.

**Comment by sivanni** [comment]
Hi, I fixed this issue and pushed it to Burbank branch. Please merge with your branches and let me know if there are any additional issues

**Comment by Vafa-Andalibi** [comment]
This is fixed in master now
