### ISSUE TITLE
Neurons to monitor have to be defined for each status monitor

### ISSUE THREAD

**Issue by henhok** [sivanni/CxSystem#44]
Now:
[St]vm[rec](0-136-30)+ge_soma[rec](0-136-30)+gi_soma[rec](0-136-30) [Sp]

Better:
[St]vm+ge_soma+gi_soma[rec](0-136-30)[Sp]

**Comment by Vafa-Andalibi** [comment]
This is for flexibility in case one wants to record part of vms but the whole ge_somas.
