### ISSUE TITLE
Cluster run: remote_output_folder plays no role?

### ISSUE THREAD

**Issue by henhok** [sivanni/CxSystem#63]
It seems the parameter remote_output_folder is not used anywhere, ie. the actual output folder in the cluster is defined by the output_path_and_filename.
 
In order for the same Anatomy config file to work for both local and cluster run (run mode could be switched with run_in_cluster flag), I suggest the following:
- output_path_and_filename refers to the LOCAL output directory
- remote_output_folder refers to the REMOTE output directory

Similar double-parameter scheme is needed for connections_loading/saving_path_and_filename.

**Comment by Vafa-Andalibi** [comment]
Cluster_run is now patched for its path issues. remote_output_folder is the remote folder where the results are saved. This must be an absolute path (with expanded user folder). The local result folder is the folder defined with output_path_and_filename .
